spring:
  application:
    name: shiro

  datasource:
    username: root
    password: lzc_123456789
    url: jdbc:mysql://localhost:3306/shiro_learn?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    show-sql: true
